[package]
name = "flo-server"
version = "0.1.0"
authors = ["pfried <philipsfried@gmail.com>"]

[dependencies]
flo-event = { path = "../flo-event" }
flo-protocol = { path = "../flo-protocol" }
num_cpus = "^1.2"
log = "0.3"
log4rs = "0.4"
clap = "2.5"
nom = "2.0"
byteorder = "0.5"
tokio-core = "0.1.4"
futures = "0.1.10"
glob = "0.2"
chrono = "^0.2"

[dev-dependencies]
env_logger = "*"
tempdir = "*"
